version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
    steps:
      - checkout # GitHubからCircleCIにソースをコピー
      - run: sudo composer self-update --1 # circleCIでPHP関連パッケージのインストールでエラーになる現象の対策
      - restore_cache:
          key: composer-v1-{{ checksum "backend/composer.lock" }}
      - run: 
          working_directory: backend
          command: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "backend/composer.lock" }}
          paths:
            - backend/vendor
      - run:
          name: php test
          working_directory: backend
          command: php artisan test